version: '3.8'

services:
    postgres:
        container_name: postgres
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-odoo}
            POSTGRES_USER: ${POSTGRES_USER:-odoo}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
            PGDATA: /var/lib/postgresql/data/pgdata
        image: postgres:${POSTGRES_VERSION:-10}
        restart: always
        volumes:
          - postgres:/var/lib/postgresql/data/pgdata

    odoo-ee:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                ODOO_VERSION: ${ODOO_VERSION:-14.0}
                ODOO_USER: ${ODOO_EE_USER:?err}
                ODOO_PASSWORD: ${ODOO_EE_PASSWORD:?err}
        command:
          - "--"
          - "--init=web_enterprise"
          - "--database=${POSTGRES_DB:-odoo}"
        container_name: odoo-ee
        depends_on:
          - postgres
        environment:
            HOST: postgres
            PORT: 5432
            USER: ${POSTGRES_USER:-odoo}
            PASSWORD: ${POSTGRES_PASSWORD:-odoo}
        ports:
          - ${ODOO_EE_PUBLISHED_PORT:-8069}:8069
        restart: always
        volumes:
#          - ./config:/etc/odoo
          - ./addons:/mnt/veone-addons
          - odoo-ee:/var/lib/odoo

    adminer:
        depends_on:
          - postgres
        image: adminer
        ports:
          - ${ADMINER_PUBLISHED_PORT:-9090}:8080
        restart: always

volumes:
    postgres:
    odoo-ee:
